version: '3'
services:
  mongodb:
    image: 'mongo:5.0'
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: 'mongo-express:0.54.0'
    container_name: mongoExpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mongoExpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoExpress
    links:
      - mongodb
    restart: always
    ports:
      - "8081:8081"

  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data


  dm-customer:
    container_name: dm-customer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: users
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres

volumes:
  pgdata: {}
networks:
  dm-customer-backend:
