POST http://localhost:8080/login/user
Content-Type: application/json

{
  "UserEmail": "karolina@karolina.com",
  "userPassword": "Password10"
}

> {% client.global.set("new-auth-token", response.body.access_token);  %}

