spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update





application:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration-time-in-millis: 1209600000
      issuer: dm-customer-backend

